name: Unit Test

on:
  push:
    branches:
    - main
    paths:
    - "_test/demo-package/**"
    - ".github/workflows/_internal-unit.yaml"
    - "unit-test/**"
    - "!(**/*.md)"
  pull_request:
    branches:
    - main
    paths:
    - "_test/demo-package/**"
    - ".github/workflows/_internal-unit.yaml"
    - "unit-test/**"
    - "!(**/*.md)"

jobs:
  unit-test:
    strategy:
      matrix:
        php_version:
          - 8.2
          - 8.3
          - 8.4
        mode:
          - standalone
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./unit-test
      with:
        source_folder: _test/demo-package
        php_version: ${{ matrix.php_version }}
        mode: ${{ matrix.mode }}
