name: Installation Test

on:
  push:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - README.md
  pull_request:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - README.md

jobs:
  compute_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.supported-version.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./supported-version
        id: supported-version
      - run: echo ${{ steps.supported-version.outputs.matrix }}

  install-test:
    needs: compute_matrix
    strategy:
      matrix: ${{ fromJSON(needs.compute_matrix.matrix) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./installation-test
      with:
        composer_version: ${{ matrix.composer }}
        php_version: ${{ matrix.php }}
        magento_version: ${{ matrix.magento }}
        composer_auth: ${{ secrets.COMPOSER_AUTH }}
        package_name: graycore/magento2-demo-package
        source_folder: $GITHUB_WORKSPACE/_test/demo-package